# Generated by Django 3.2.16 on 2023-07-12 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmodel',
            old_name='description',
            new_name='message',
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
